<?php
add_action( 'widgets_init', 'flickr_load_widgets' );

function flickr_load_widgets() {
	register_widget( 'Daydream_Flickr_Widget' );
}

class Daydream_Flickr_Widget extends WP_Widget {

	public function __construct() {
		parent::__construct(
		'flickr-widget', __( 'daydream: Flickr', 'daydream' ), // Name
		       array( 'classname' => 'flickr', 'description' => __( 'The most recent photos from flickr.', 'daydream' ), ) // Args		
		);
	}

	public function widget( $args, $instance ) {
		extract( $args );

		$title = apply_filters( 'widget_title', $instance[ 'title' ], $instance, $this->id_base );
		$screen_name	 = $instance[ 'screen_name' ];
		$number		 = $instance[ 'number' ];
		$api		 = $instance[ 'api' ];

		echo $before_widget;

		if ( $title ) {
			echo $before_title . $title . $after_title;
		}

		if ( $screen_name && $number && $api ) {
			?>
			<script type="text/javascript">
				function jsonFlickrApi(rsp) {
				    if (rsp.stat != "ok") {
					// If this executes, something broke!
					return;
				    }

				    //variable "s" is going to contain 
				    //all the markup that is generated by the loop below
				    var s = "";

				    //this loop runs through every item and creates HTML 
				    for (var i = 0; i < rsp.photos.photo.length; i++) {
					photo = rsp.photos.photo[ i ];

					//notice that "t.jpg" is where you change the
					//size of the image
					t_url = "http://farm" + photo.farm +
						".static.flickr.com/" + photo.server + "/" +
						photo.id + "_" + photo.secret + "_" + "s.jpg";

					p_url = "http://www.flickr.com/photos/" +
						photo.owner + "/" + photo.id;

					s += '<div class="flickr_badge_image"><a href="' + p_url + '">' + '<img alt="' +
						photo.title + '"src="' + t_url + '"/>' + '</a></div>';
				    }

				    document.write(s);
				}
			</script>
			<script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;user_id=<?php echo $screen_name; ?>&amp;api_key=<?php echo $api; ?>&amp;media=photos&amp;per_page=<?php echo $number; ?>&amp;privacy_filter=1"></script>
			<script type="text/javascript" src="https://api.flickr.com/services/rest/?format=json&amp;method=flickr.photos.search&amp;group_id=<?php echo $screen_name; ?>&amp;api_key=<?php echo $api; ?>&amp;media=photos&amp;per_page=<?php echo $number; ?>&amp;privacy_filter=1"></script>
			<?php
		}

		echo $after_widget;
	}

	public function update( $new_instance, $old_instance ) {
		$instance = $old_instance;

		$instance[ 'title' ]		 = strip_tags( sanitize_text_field($new_instance[ 'title' ]) );
		$instance[ 'screen_name' ]	 = sanitize_text_field($new_instance[ 'screen_name' ]);
		$instance[ 'number' ]		 = sanitize_text_field($new_instance[ 'number' ]);
		$instance[ 'api' ]		 = sanitize_text_field($new_instance[ 'api' ]);

		return $instance;
	}

	public function form( $instance ) {
		$defaults	 = array( 'title' => 'Flickr Images', 'screen_name' => '', 'number' => 8, 'api' => '' );
		$instance	 = wp_parse_args( (array) $instance, $defaults );
		?>

		<p>
		    <label for="<?php echo esc_attr($this->get_field_id( 'title' )); ?>"><?php echo esc_html_e( 'Title', 'daydream' ); ?></label>
		    <input class="widefat" type="text" id="<?php echo esc_attr($this->get_field_id( 'title' )); ?>" name="<?php echo esc_attr($this->get_field_name( 'title' )); ?>" value="<?php echo esc_attr($instance[ 'title' ]); ?>" />
		</p>

		<p>
		    <label for="<?php echo esc_attr($this->get_field_id( 'screen_name' )); ?>"><?php echo esc_html_e( 'Flickr ID(<a href="http://idgettr.com/">Get your flickr ID</a>)', 'daydream' ); ?></label>
		    <input class="widefat" type="text" id="<?php echo esc_attr($this->get_field_id( 'screen_name' )); ?>" name="<?php echo esc_attr($this->get_field_name( 'screen_name' )); ?>" value="<?php echo esc_attr($instance[ 'screen_name' ]); ?>" />
		</p>


		<p>
		    <label for="<?php echo esc_attr($this->get_field_id( 'number' )); ?>"><?php echo esc_html_e( 'Number of photos to show', 'daydream' ); ?></label>
		    <input class="widefat" type="text" style="width: 30px;" id="<?php echo esc_attr($this->get_field_id( 'number' )); ?>" name="<?php echo esc_attr($this->get_field_name( 'number' )); ?>" value="<?php echo esc_attr($instance[ 'number' ]); ?>" />
		</p>

		<p>
		    <label for="<?php echo esc_attr($this->get_field_id( 'api' )); ?>"><?php echo esc_html_e( 'API key (Use default or get your own from <a href="http://www.flickr.com/services/apps/create/apply">Flickr APP Garden</a>)', 'daydream' ); ?></label>
		    <input class="widefat" type="text" id="<?php echo esc_attr($this->get_field_id( 'api' )); ?>" name="<?php echo esc_attr($this->get_field_name( 'api' )); ?>" value="<?php echo esc_attr($instance[ 'api' ]); ?>" />
		</p>

		<?php
	}

}
